version: "3.4"

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
       - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8032:8080